POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlYWN0IiwiaWQiOiI2MmYyOWFmYWE5OTI5ZWEwYTBmNTM2YTciLCJpYXQiOjE2NjAwNjY1NzZ9.MOUvYHQD3VDcmubid3luLH9nZm8I0GvSJdKINBJPqkw

{
    "title":"How to win people and win friends",
    "author":"Dale Carnegie",
    "url":"winpeople.com",
    "likes":1110
}


###
GET http://localhost:3001/api/blogs


###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"react",
    "name":"React",
    "password":"react123"
}