POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Atomic habbits",
  "author": "Subash",
  "url": "sommeurl.com",
  "likes": 9
}


###
GET http://localhost:3001/api/blogs


###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"react",
    "name":"React",
    "password":"react123"
}